apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
  app: hello-kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-kubernetes
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: hello-kubernetes-deploy
  namespace: default
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: hello-kubernetes
      app: hello-kubernetes
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: hello-kubernetes
      template:
        metadata:
          labels:
            app: hello-kubernetes
        spec:
          containers:
          - name: hello-kubernetes
            image: paulbouwer/hello-kubernetes:1.8
            imagePullPolicy: Always
            ports:
            - containerPort: 8080
