apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes1
  app: hello-kubernetes
  labels:
    environment: test
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-kubernetes

